import type {
  AgendaTask,
  MeetingDetail,
  TodaySnapshot,
  WeekSnapshot,
} from '../../src/lib/domain/agenda';
import { newMeetingDraft } from '../../src/lib/domain/agenda-calendar';
export const project = {
  id: 'p',
  name: 'Atlas',
  color: 'cyan' as const,
  manager_name: null,
  manager_email: null,
  summary_send_at: null,
  summary_tone: 'brief' as const,
  sort_order: 0,
};
export const task: AgendaTask = {
  id: 't',
  project_id: 'p',
  project_name: 'Atlas',
  project_color: 'cyan',
  title: 'Keep the deadline',
  status: 'todo',
  priority: 'medium',
  due_at: '2025-09-12T15:30:12.345Z',
  estimate_h: 2,
  hours_worked: 1,
  external_url: null,
  external_id: 'ATL-1',
  external_provider: null,
  blocked_reason: null,
  blocked_on: null,
  notes_md: '',
  created_at: '2025-09-01T00:00:00Z',
  updated_at: '2025-09-01T00:00:00Z',
  done_at: null,
  blocked_since: null,
  sort_order: 0,
  revision: 0,
  tags: [],
  subtask_done: 0,
  subtask_total: 0,
  planned_ranges: [],
};
export const meeting: MeetingDetail = {
  occurrence: {
    ...newMeetingDraft('2025-09-12T12:00:00Z', 'UTC'),
    starts_at: '2025-09-12T12:15:00.000Z',
    start_local: '2025-09-12T12:15:00.000',
    id: 'occ',
    project_id: 'p',
    project_name: 'Atlas',
    project_color: 'cyan',
    title: 'Review',
    ref: { meetingId: 'm', occurrenceKey: 'o:0' },
    revision: 4,
    attendance: 'unmarked',
    occurrence_notes_md: '',
  },
  series: {
    is_recurring: false,
    repeat_rule: 'none',
    repeat_until: null,
    fold_policy: 'earlier',
    revision: 4,
  },
  linked_tasks: [],
};
export const days = Array.from({ length: 7 }, (_, i) => ({
  date: `2025-09-${String(8 + i).padStart(2, '0')}`,
  tasks: i === 4 ? [task] : [],
  meetings: i === 4 ? [meeting.occurrence] : [],
}));
export const today: TodaySnapshot = {
  query: { date: '2025-09-12', timeZone: 'UTC' },
  today: '2025-09-12',
  week_start: '2025-09-08',
  days,
  overdue: [],
  due_today: [task],
  tomorrow: [],
  meetings: [meeting.occurrence],
  hours_this_week: [
    { project_id: 'p', project_name: 'Atlas', project_color: 'cyan', hours: 1 },
  ],
  counts: { overdue: 0, due_today: 1, tomorrow: 0, meetings: 1 },
  fingerprint: 'f',
  skipped_dates: [],
};
export const week: WeekSnapshot = {
  query: { date: '2025-09-12', timeZone: 'UTC', projectId: 'p' },
  today: '2025-09-12',
  project,
  week_start: '2025-09-08',
  days,
  later: [],
  no_date: [],
  overdue_before_week: [],
  overdue_counts: {},
  fingerprint: 'f',
  skipped_dates: [],
};
